[[redirects]]
from = "/qq"
to = "https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=qBP7Ss78sT68OOSMO5mpzAgp5Py3sOKJ&authKey=3I0V1ckK1NCWK%2BmKKZskA6oi6BgA96z1pipSaUjGxgXs%2Br3qPp3aV%2BbChu%2FjPjjO&noverify=0&group_code=975714136"
status = 302